image: ubuntu:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq autoconf build-essential git libtool lcov gcovr
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - ./bootstrap

build:
  stage: build
  script:
    - ./configure
    - make

test:
  stage: test
  script:
    - ./configure --enable-code-coverage
    - make check
    - gcovr -sr .
