image: ubuntu:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential cmake git lcov gcovr
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - cmake ./
    - make

test:
  stage: test
  script:
    - cmake -DENABLE_CODE_COVERAGE=ON ./
    - make check
    - gcovr -sr . -e '.*/main.cpp' -e '.*/\.' -e '3rdparty'
