stages:
  - build
  - test

builder:
  stage: build
  script:
    - ./bootstrap
    - ./configure
    - make -j `nproc --all`

tester:
  stage: test
  script:
    - git submodule init
    - git submodule update
    - ./bootstrap
    - ./configure --enable-code-coverage
    - make -j `nproc --all` check
    - gcovr -r .
