image: ubuntu:latest

before_script:
  - apt-get update && apt-get install -y --no-install-recommends build-essential ca-certificates cmake git lcov gcovr ninja-build

build:
  stage: build
  script:
    - cmake -H. -Bbuild/ -G Ninja
    - cmake --build build/

test:
  stage: test
  script:
    - cmake -H. -Bbuild/ -G Ninja -DENABLE_CODE_COVERAGE=ON
    - cmake --build build/ --target check
    - gcovr -sr build/ -e '.*/main.cpp' -e '.*googletest.*'
